# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-23 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_no', models.PositiveSmallIntegerField()),
                ('title', models.TextField()),
                ('remark', models.TextField()),
                ('mode', models.PositiveSmallIntegerField()),
                ('printed_in', models.TextField()),
                ('genre', models.TextField()),
                ('scribe', models.TextField()),
            ],
        ),
    ]
