# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-23 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='mode',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='composition',
            name='track_no',
            field=models.SmallIntegerField(),
        ),
    ]
